devmode = false

[log]
  file = ""

[srv]
  host = "0.0.0.0"
  port = 8432
  # IPs exempt from ratelimiting.
  ratelimit_exempt = [
    "192.168.0.0/16",
  ]
  trusted_proxies = [
    "127.0.0.1"
  ]
  api_version = "1.0.0"

[pages]
  frontend_version = "1.0.0"